#!/bin/bash

custard - configure \
    grid.rows               2 \
    grid.columns            3 \
    grid.margins            0 \
    grid.margin.top         0 \
    grid.margin.bottom      0 \
    grid.margin.left        0 \
    grid.margin.right       0 \
    borders                 0 \
    border.size.inner       0 \
    border.size.outer       0 \
    border.color.focused    '#ffffffff' \
    border.color.unfocused  '#676767ff' \
    border.color.background '#000000ff' \
    workspaces              1

sxhkd -c ~/.config/sxhkdrc &
